inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
      - 'db/schema.rb'
      - 'bin/**/*'

AlignHash:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
