create_ask_jobs_for_today:
  cron: "0 0 * * * Europe/Paris"
  class: "CreateAskPriestJobsForTodayJob"
  queue: default
  description: "This job creates jobs to ask priests availability today"
cleanup_dynamic_spots:
  every:
    - "15m"
    - :first_in: '120s'
  class: "CleanupDynamicSpotsJob"
  queue: default
  description: "This job removes outdated dynamic spots"
cleanup_outdated_meet_requests:
  every:
    - "15m"
    - :first_in: '120s'
  class: "CleanupOutdatedMeetRequestJob"
  queue: default
  description: "This job removes outdated meet requests"
cleanup_outdated_messages:
  every:
    - "15m"
    - :first_in: '120s'
  class: "CleanupOutdatedMessagesJob"
  queue: default
  description: "This job removes outdated messages"
