development:
  secret_key_base: 66e761a96d150c6da37e1f340351d6c1aff65eb9db05d265d765099405f2cf6319fe43cd895d48b05cf557cb6303f3f6d07b7eb25ef6bc919b385801846cd89b
  domain_name: 0.0.0.0:3000
  android_push_key: <%= ENV["ANDROID_PUSH_KEY"] %>
  pusher_app_id: 201183
  pusher_key: 431f7475e961c95db8f3
  pusher_secret: b83a3533599f25a00da1
  pusher_cluster: eu
  fcm_server_key: AIzaSyBGcK8_B6vsx3m8QhSvQW2goFkAwL1nFGw

test:
  secret_key_base: 24e7ec2e8b5cfd174d4fd9e9483f78e6a62b41b0bdb2616864e8486b3e44fe44457b415ee4dccdd0546916d354b2262bbf4936c3997a568ce46f8774df40e9f6
  android_push_key: AIzaSyARO7z7orvKjMTmDEJc0iG8ROEJyVWcYb0
  fcm_server_key: AIzaSyBGcK8_B6vsx3m8QhSvQW2goFkAwL1nFGw

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_key: <%= ENV["POSTMARK_API_KEY"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  android_push_key: <%= ENV["ANDROID_PUSH_KEY"] %>
  pusher_app_id: <%= ENV["PUSHER_APP_ID"] %>201120
  pusher_key: <%= ENV["PUSHER_KEY"] %>
  pusher_secret: <%= ENV["PUSHER_SECRET"] %>
  pusher_cluster: <%= ENV["PUSHER_CLUSTER"] %>
  fcm_server_key: <%= ENV["FCM_SERVER_KEY"] %>
